### ISSUE TITLE
安装空调狗后显示此设备由您的所属单位管理

### ISSUE THREAD

**Issue by Blusez** [zsh2401/AutumnBox#13]
安装空调狗后显示此设备由您的所属单位管理

**Comment by MonoLogueChi** [comment]
请看空调狗FAQ

**Comment by Blusez** [comment]
> 请看空调狗FAQ

能提供一下地址吗？ 十分感谢

**Comment by xxxxxliil** [comment]
> > 请看空调狗FAQ
> 
> 能提供一下地址吗？ 十分感谢

你这个问题是 Android 系统的特性，无法关掉
