### ISSUE TITLE
can you fix the wiki???

### ISSUE THREAD

**Issue by PowerOlive** [zsh2401/AutumnBox#15]
https://github.com/zsh2401/AutumnBox/wiki/zh_CN_AutumnBox%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3

**Comment by MonoLogueChi** [comment]
Sorry, I haven't processed the issue for a while, because the AutumnBox is in the process of development, the development documentation has not been updated yet, and the development documentation will be compiled in the future.
