### ISSUE TITLE
建议更改shizuku的adb激活命令

### ISSUE THREAD

**Issue by unohara-fuukei** [zsh2401/AutumnBox#45]
建议更改shizuku的adb激活命令，新版shizuku用2019版秋之盒会执行错误地址的sh文件

**Comment by unohara-fuukei** [comment]
关联issue：
https://github.com/zsh2401/AutumnBox/issues/43#issue-1461154090

**Comment by unohara-fuukei** [comment]
回顾了一下前序issue，开发者已停止开发，故关闭请求。辛苦了。

**Comment by HSSkyBoy** [comment]
> 回顾了一下前序issue，开发者已停止开发，故关闭请求。辛苦了。

搞个pr，他不就直接同意了... 人家不开发，但单单修改一个文件，确认没问题直接合并还是有时间的
现在已经完成合并了
