### ISSUE TITLE
使用激活shizuku过程中遇到的问题及自行解决思路

### ISSUE THREAD

**Issue by saltglow** [zsh2401/AutumnBox#48]
机型:product::HONOR,KOZ-AL00

问题如下:
正在初始化
sh: /sdcard/Android/data/moe.shizuku.privileged.api/files/start.sh: No such file or directory
执行完成,退出码:127

解决办法:
将/sdcard/Android/data/moe.shizuku.privileged.api/下的start.sh和starter两个文件
转移到/sdcard/Android/data/moe.shizuku.privileged.api/files/这个路径下

议论:完全就搞不清楚这个到底是为什么发生的 bug,但是经过这样调试之后，确实就好了，确实能够运行成功了
![屏幕截图 2024-02-01 132252](https://github.com/zsh2401/AutumnBox/assets/143920014/9a1e7882-e4c8-4c1d-b66a-762bcf06ea81)

**Comment by HSSkyBoy** [comment]
因为新版本Shizuku修改了激活文件的储存地址，所以原先的当然不行了

**Comment by saltglow** [comment]
千谢解惑
