### ISSUE TITLE
English, Ukrainian, Russian translations

### ISSUE THREAD

**Issue by bullik01** [zsh2401/AutumnBox#8]
Hello guys! What you think about English, Ukrainian, Russian translations?

**Comment by zsh2401** [comment]
oh my god,you are my first non-chinese user.
In fact, my English is not good, so the software is very difficult even if it is English

**Comment by bullik01** [comment]
Why it very difficult? No! It's simple (i think) for non-tech user... And this is good! So what you think about translation?

And... Additionaly i can introduce this software in russian tech forum 4pda.ru... But first... We need translation...

Sooooo.... I wait for your reply :)

**Comment by zsh2401** [comment]
@bullik01 English translation in development, Russian and Ukrainian only machine translation

**Comment by bullik01** [comment]
I can do good English, Ukrainian, Russian translations. I'm from Ukraine :)

**Comment by zsh2401** [comment]
@bullik01 English translation is finished,you can use  AutumnBox.GUI/I18N/Langs/en-US.xaml to do other language translations.

**Comment by bullik01** [comment]
Ok. Thanks
