### ISSUE TITLE
希望能通过adb利用提权漏洞root设备

### ISSUE THREAD

**Issue by xiebincnz** [zsh2401/AutumnBox#9]
希望能通过adb利用提权漏洞root设备.想给电视root删除开机广告,结果没有几个APP能够一键root,而电脑版的root软件却不支持用网络adb连接电视.鉴于这是一款对小白友好的工具箱,因此希望能集成这个功能.(ps:电视是安卓5.1.1的)

**Comment by zsh2401** [comment]
无法实现
